### ISSUE TITLE
skipcount parameter for  listunspent and listtransactions calls does not work

### ISSUE THREAD

**Issue by SirSevenG** [jl777/libnspv#37]
'skipcount' parameter has currently no effect.

To reporduce:

* take address with X amount of utxos/transactions
* call listtransactions with skipcount = 0
* call listtransactions with skipcount = N, N > 0

result: calls have same output
expected: 2nd call should have N less transactions/utxos in output

Curls might be used to check (for KMD):
```shell
curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "listtransactions", "params": ["RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh", 0, 0] }' -H 'content-type: text/plain;' http://127.0.0.1:7771/

curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "listtransactions", "params": ["RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh", 0, 30] }' -H 'content-type: text/plain;' http://127.0.0.1:7771/

curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "listunspent", "params": ["RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh", 0, 0] }' -H 'content-type: text/plain;' http://127.0.0.1:7771/

curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "listunspent", "params": ["RBCSvPzYtTZ51RYbsDLKkQ58Mj5TuRRNeh", 0, 30] }' -H 'content-type: text/plain;' http://127.0.0.1:7771/
```

**Comment by jl777** [comment]
should be fixed in the latest version

**Comment by SirSevenG** [comment]
Problem persists:

```shell
curl --data-binary '{"jsonrpc": "2.0", "id":"curltest", "method": "listunspent", "params": ["__address__", 0, "15"] }' -H 'content-type: text/plain;' http://127.0.0.1:12986/ 
```
```json
{"result":"success","utxos":[__utxos__],"address":"__address__","isCC":0,"height":14033,"numutxos":40,"balance":0.3196,"rewards":0,"skipcount":0,"filter":0,"lastpeer":"5.9.253.198:12985"}
```
commit: dc8cc1eeda76be240da322780b47c064c29a4482

Note above: skipcount param i pass in curl = 15 and skipcount = 0 in respone.
Does not matter how i pass it, always 0.

**Comment by jl777** [comment]
ok, will investigate

**Comment by SirSevenG** [comment]
Libnspv
Works correctly at 89b115adb2ab903c37cd0cc08a465404b2114a15

komodod
Does not work at 450ac5c5ea758de4b6ae4a858e811c54ca984983

- always returns all utxos as ``` "numutxos": _num_ ``` no matter the skipcount

**Comment by jl777** [comment]
please retest this and make sure you use a seednode that is an nSPV fullnode
mihailo tested with komodod and it works for him now

**Comment by SirSevenG** [comment]
Works on both komodod and libnspv correctly now.
